# Generated by Django 5.1 on 2024-08-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['name'], 'verbose_name': 'Dish Type', 'verbose_name_plural': 'Dish Types'},
        ),
    ]
