# Generated by Django 4.1 on 2024-09-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_ingredient_dish_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'ingredient', 'verbose_name_plural': 'ingredients'},
        ),
    ]
